# Generated by Django 6.0.2 on 2026-05-05 15:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionheader',
            name='vat_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='transactionheader',
            name='vat_exempt_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='transactionheader',
            name='vat_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.12'), max_digits=5),
        ),
        migrations.AddField(
            model_name='transactionheader',
            name='vatable_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='transactionheader',
            name='zero_rated_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
    ]
