# Generated by Django 6.0.2 on 2026-03-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(max_length=8)),
                ('pcode', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('tender_desc', models.CharField(blank=True, max_length=15)),
            ],
            options={
                'db_table': 'payments',
                'indexes': [models.Index(fields=['transaction_no'], name='payments_transac_fb6c7d_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransactionTenderCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(max_length=8)),
                ('pcode', models.CharField(max_length=3)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'transaction_tender_counts',
                'indexes': [models.Index(fields=['transaction_no'], name='transaction_transac_cd3a0f_idx')],
                'unique_together': {('transaction_no', 'pcode')},
            },
        ),
    ]
