# Generated by Django 6.0.3 on 2026-03-27 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionheader',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_headers', to='users.possession'),
        ),
        migrations.AddField(
            model_name='payment',
            name='header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.transactionheader'),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.transactionheader'),
        ),
        migrations.AddIndex(
            model_name='transactiontendercount',
            index=models.Index(fields=['transaction_no'], name='transaction_transac_cd3a0f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transactiontendercount',
            unique_together={('transaction_no', 'pcode')},
        ),
        migrations.AddIndex(
            model_name='transactionheader',
            index=models.Index(fields=['transaction_no', 'transaction_date'], name='transaction_transac_f9e16d_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionheader',
            index=models.Index(fields=['store_id', 'terminal_id', 'transaction_date'], name='transaction_store_i_5febb9_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['header'], name='payment_header__1f0055_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionitem',
            index=models.Index(fields=['item_code'], name='transaction_item_co_6077e6_idx'),
        ),
    ]
