# Generated by Django 6.0.2 on 2026-05-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_transactionheader_vat_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalconfiguration',
            name='store_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
