# Generated by Django 6.0.2 on 2026-03-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalconfiguration',
            name='print_in',
            field=models.CharField(choices=[('SERIAL', 'Serial'), ('USB', 'USB'), ('NETWORK', 'Network')], default='SERIAL', max_length=10),
        ),
        migrations.AddField(
            model_name='terminalport',
            name='connection_type',
            field=models.CharField(choices=[('SERIAL', 'Serial'), ('USB', 'USB'), ('NETWORK', 'Network')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='terminalport',
            name='port_name',
            field=models.CharField(max_length=15),
        ),
    ]
