# Generated by Django 6.0.3 on 2026-03-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalreceiptfooter',
            name='is_centered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='terminalreceiptfooter',
            name='is_left_align',
            field=models.BooleanField(default=False),
        ),
    ]
