# Generated by Django 6.0.2 on 2026-03-18 13:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_payment_transactiontendercount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='TerminalConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=3)),
                ('terminal_id', models.CharField(max_length=3)),
                ('vat', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('open_time', models.TimeField(default=datetime.time(9, 0))),
                ('cutoff_time', models.TimeField(default=datetime.time(4, 0))),
            ],
            options={
                'db_table': 'terminal_configurations',
                'unique_together': {('store_id', 'terminal_id')},
            },
        ),
        migrations.CreateModel(
            name='TerminalDisplayCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_group', models.CharField(max_length=2)),
                ('code_value', models.CharField(blank=True, max_length=5)),
                ('code_length', models.CharField(blank=True, max_length=2)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='display_codes', to='sales.terminalconfiguration')),
            ],
            options={
                'db_table': 'terminal_display_codes',
            },
        ),
        migrations.CreateModel(
            name='TerminalPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_type', models.CharField(choices=[('PRINTER', 'Printer'), ('DRAWER', 'Cash Drawer'), ('DISPLAY', 'Pole Display')], max_length=10)),
                ('port_name', models.CharField(max_length=10)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ports', to='sales.terminalconfiguration')),
            ],
            options={
                'db_table': 'terminal_ports',
            },
        ),
        migrations.CreateModel(
            name='TerminalReceiptFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveSmallIntegerField()),
                ('footer_text', models.CharField(max_length=40)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='footers', to='sales.terminalconfiguration')),
            ],
            options={
                'db_table': 'terminal_receipt_footers',
                'ordering': ['line_number'],
            },
        ),
        migrations.CreateModel(
            name='TerminalReceiptHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveSmallIntegerField()),
                ('header_text', models.CharField(max_length=40)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='headers', to='sales.terminalconfiguration')),
            ],
            options={
                'db_table': 'terminal_receipt_headers',
                'ordering': ['line_number'],
            },
        ),
    ]
