# Generated by Django 6.0.3 on 2026-05-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='change_amount',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Change returned for this tender line. Non-zero for cash only.', max_digits=15),
        ),
        migrations.AddField(
            model_name='payment',
            name='tendered_amount',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Gross amount handed over. Equals amount for non-cash.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
