# Generated by Django 6.0.3 on 2026-04-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_terminalreceiptfooter_is_centered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalreceiptheader',
            name='is_capitalized',
            field=models.BooleanField(default=False),
        ),
    ]
