# Generated by Django 6.0.2 on 2026-03-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_terminalconfiguration_print_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalport',
            name='baudrate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terminalport',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='terminalport',
            name='port_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terminalport',
            name='printer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='terminalport',
            name='connection_type',
            field=models.CharField(choices=[('SERIAL', 'Serial'), ('USB', 'USB'), ('NETWORK', 'Network'), ('WINDOWS', 'Windows')], max_length=10),
        ),
        migrations.AlterField(
            model_name='terminalport',
            name='port_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
