# Generated by Django 6.0.3 on 2026-06-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_payment_change_amount_payment_tendered_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspendedtransaction',
            name='item_color_desc',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
