# Generated by Django 6.0.2 on 2026-05-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_terminalconfiguration_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tax_code',
            field=models.CharField(blank=True, default='1', max_length=1),
        ),
    ]
