# Generated by Django 4.2.28 on 2026-07-21 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('sales', '0004_suspendedtransaction_item_color_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashInOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Cash In'), ('OUT', 'Cash Out')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=120)),
                ('approved_by', models.CharField(blank=True, max_length=60)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_movements', to='users.possession')),
            ],
            options={
                'db_table': 'cash_inout',
                'indexes': [models.Index(fields=['session', 'movement_type'], name='cash_inout_session_6b260b_idx'), models.Index(fields=['created_at'], name='cash_inout_created_923223_idx')],
            },
        ),
    ]
