# Generated by Django 6.0.2 on 2026-05-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_item_tax_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tax_code',
            field=models.CharField(blank=True, default='V', max_length=1),
        ),
    ]
