# Generated by Django 4.2.28 on 2026-07-21 21:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_cashinout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionheader',
            name='vat_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.12'), max_digits=8),
        ),
    ]
