# Generated by Django 6.0.2 on 2026-05-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_item_tax_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='color_desc',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='item_color_desc',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
