# Generated by Django 6.0.2 on 2026-05-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_item_color_desc_transactionitem_item_color_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='temptransaction',
            name='item_color_desc',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
