# Generated by Django 4.2.28 on 2026-08-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_transactionheader_vat_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminalconfiguration',
            name='print_in',
            field=models.CharField(choices=[('SERIAL', 'Serial'), ('USB', 'USB'), ('NETWORK', 'Network'), ('WINDOWS', 'Windows'), ('FILE', 'File (No Printer / Dev-Testing)')], default='SERIAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='terminalport',
            name='connection_type',
            field=models.CharField(choices=[('SERIAL', 'Serial'), ('USB', 'USB'), ('NETWORK', 'Network'), ('WINDOWS', 'Windows'), ('FILE', 'File (No Printer / Dev-Testing)')], max_length=10),
        ),
    ]
