# Generated by Django 6.0.2 on 2026-05-07 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_temptransaction_item_color_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='color_desc',
        ),
    ]
