# Generated by Django 6.0.3 on 2026-09-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_terminalconfiguration_print_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionheader',
            name='user_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='transactionheader',
            name='user_id2',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
