# Generated by Django 6.0.3 on 2026-09-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_transactionheader_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='approval_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='holder',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
