# Generated by Django 6.0.2 on 2026-05-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_remove_item_color_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdetail',
            name='color_desc',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
