# Generated by Django 6.0.3 on 2026-09-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_payment_approval_code_payment_holder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='holder',
        ),
        migrations.AddField(
            model_name='payment',
            name='card_number_masked',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='cardholder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='approval_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
