# Generated by Django 6.0.3 on 2026-09-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_remove_payment_holder_payment_card_number_masked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='is_card',
            field=models.BooleanField(default=False),
        ),
    ]
