# Generated by Django 6.0.2 on 2026-03-05 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('cashier', 'Cashier'), ('supervisor', 'Supervisor'), ('manager', 'Manager'), ('admin', 'Admin')], default='cashier', max_length=20)),
                ('middle_initial', models.CharField(blank=True, default='', max_length=1)),
                ('suffix', models.CharField(blank=True, default='', max_length=6)),
                ('store_id', models.CharField(blank=True, default='001', max_length=3)),
                ('terminal_id', models.CharField(blank=True, default='001', max_length=3)),
                ('is_suspended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
