# Generated by Django 6.0.2 on 2026-05-04 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSSessionUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pos_session_users',
            },
        ),
        migrations.RemoveField(
            model_name='possession',
            name='cashier',
        ),
        migrations.AddField(
            model_name='possession',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='possession',
            name='opened_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='opened_sessions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='possession',
            index=models.Index(fields=['store_id', 'business_date'], name='pos_session_store_i_3fccea_idx'),
        ),
        migrations.AddIndex(
            model_name='possession',
            index=models.Index(fields=['status'], name='pos_session_status_197bb1_idx'),
        ),
        migrations.AddField(
            model_name='possessionusers',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_users', to='users.possession'),
        ),
        migrations.AddField(
            model_name='possessionusers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='possessionusers',
            index=models.Index(fields=['session', 'left_at'], name='pos_session_session_22c102_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='possessionusers',
            unique_together={('session', 'user')},
        ),
    ]
