# Generated by Django 6.0.2 on 2026-03-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='possession',
            name='store_id',
            field=models.CharField(default='001', max_length=10),
        ),
    ]
