# Generated by Django 4.2.28 on 2026-03-22 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_possession_store_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='auth_user',
        ),
    ]
