# Generated by Django 6.0.2 on 2026-04-18 23:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=3)),
                ('terminal_id', models.CharField(max_length=3)),
                ('vat', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('open_time', models.TimeField(default=datetime.time(9, 0))),
                ('cutoff_time', models.TimeField(default=datetime.time(4, 0))),
            ],
            options={
                'db_table': 'terminal_setup',
                'unique_together': {('store_id', 'terminal_id')},
            },
        ),
    ]
