# Generated by Django 6.0.2 on 2026-05-04 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalFileDirectories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_path', models.CharField(max_length=255)),
                ('items_csv_path', models.CharField(blank=True, max_length=255)),
                ('itemdtl_csv_path', models.CharField(blank=True, max_length=255)),
                ('itemscosts_csv_path', models.CharField(blank=True, max_length=255)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_directories', to='sales.terminalconfiguration')),
            ],
            options={
                'db_table': 'terminal_file_directories',
            },
        ),
    ]
